server:
  # Render inyecta su propio puerto dinámicamente en la variable PORT
  port: ${PORT:9000}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
          routes:
            # Usamos variables para que el Gateway sepa a qué URL de Render redirigir el tráfico
            - id: identity-service
              uri: ${IDENTITY_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/api/v1/auth/**

            - id: routing-service
              uri: ${ROUTING_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/routes/**

            - id: tracking-service
              uri: ${TRACKING_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/tracking/**, /api/v1/demand/**