server:
  port: ${PORT:9000}

# --- NUEVO: Configuración del Secreto JWT ---
jwt:
  secret: ${JWT_SECRET:ChapaTuRutaSecretKeyParaFirmarLosTokensJWTDeFormaSegura2026}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # 1. Configuración global de CORS directamente bajo "gateway"
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # 2. Lista de rutas directamente bajo "gateway"
      routes:
        - id: identity-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/v1/auth/**, /api/v1/companies/**
          filters:
            - JwtAuthentication # Ahora sí encontrará el bean de tu filtro correctamente

        - id: routing-service
          uri: ${ROUTING_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/routes/**
          filters:
            - JwtAuthentication

        - id: tracking-service
          uri: ${TRACKING_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/tracking/**, /api/v1/demand/**
          filters:
            - JwtAuthentication